# Generated by Django 5.1.7 on 2025-03-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneSas_app', '0003_portfolioimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='image',
            new_name='main_image',
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.ImageField(upload_to='portfolio/images/'),
        ),
    ]
