# Generated by Django 5.1.7 on 2025-03-26 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneSas_app', '0004_rename_image_portfolioitem_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='client',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.ImageField(upload_to='portfolio/additional/'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='portfolio_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='OneSas_app.portfolioitem'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='main_image',
            field=models.ImageField(upload_to='portfolio/main/'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
