# Generated by Django 5.1.7 on 2025-03-26 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneSas_app', '0006_alter_portfolioitem_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='project_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
