# Generated by Django 5.1.7 on 2025-03-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneSas_app', '0007_alter_portfolioitem_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='project_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
