# Generated by Django 5.1.7 on 2025-05-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneSas_app', '0009_alter_portfolioitem_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
